"""
Django settings for sales_and_finance project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
# from decouple import config

# Path dasar proyek
BASE_DIR = Path(__file__).resolve().parent.parent

# Konfigurasi Media
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Konfigurasi Static Files
STATIC_URL = "static/"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-agt1jdcq+w%2t&0f+w1f9qrhkk4g!j)((s3y7!kjzwz6)ge7zc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# settings.py
# from decouple import config
# GUPSHUP_API_KEY = config('GUPSHUP_API_KEY')
# GUPSHUP_SOURCE_NUMBER = config('GUPSHUP_SOURCE_NUMBER')

# settings.py
GUPSHUP_API_KEY = 'sk_49b512570561442898bf2a6cb4b4c001' 
GUPSHUP_SOURCE_NUMBER = '917834811114'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # add depedencies
    'rest_framework',
    'stock',
    'sales',
    'finance',
    'notifications',
    'corsheaders',
    'django_filters',
]

MIDDLEWARE = [
    #install cors
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sales_and_finance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'stock/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sales_and_finance.wsgi.application'

# Mengizinkan akses dari frontend React
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://172.20.10.3:5001"
]



# Jika ingin mengizinkan semua domain (tidak disarankan untuk production)
CORS_ALLOW_ALL_ORIGINS = True  # (Opsional, hanya gunakan saat testing)

# Mengizinkan metode yang boleh diakses
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS",
]

# Mengizinkan header tertentu dalam request
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
]


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'sales_and_finance_db',  # Ganti dengan nama database MySQL
#         'USER': 'root',  # Ganti dengan username MySQL
#         'PASSWORD': '',  # Ganti dengan password MySQL
#         'HOST': 'localhost',  # Jika menggunakan server lain, ganti sesuai kebutuhan
#         'PORT': '3306',  # Port default MySQL
#         'OPTIONS': {
#             'charset': 'utf8mb4',  # Menggunakan utf8mb4 agar mendukung emoji dan karakter khusus
#         },
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dairytrack_operation',  # Ganti dengan nama database MySQL
        'USER': 'dairytrack_operation',  # Ganti dengan username MySQL
        'PASSWORD': 'c89d2e129b1b9d76b283c5989a33ef05f9cb88d2',  # Ganti dengan password MySQL
        'HOST': 'd2pug.h.filess.io',  # Jika menggunakan server lain, ganti sesuai kebutuhan
        'PORT': '61002',  # Port default MySQL
        'OPTIONS': {
            'charset': 'utf8mb4',  # Menggunakan utf8mb4 agar mendukung emoji dan karakter khusus
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',  # Tambahkan parser ini
        'rest_framework.parsers.MultiPartParser',
    ],
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'whatsapp_errors.log',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}