# Generated by Django 5.1.3 on 2025-05-14 08:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMilk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_id', models.IntegerField()),
                ('production_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('volume_liters', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(default='fresh', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_total_id', models.IntegerField(blank=True, null=True)),
                ('session', models.IntegerField()),
                ('available_stocks', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'raw_milks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('role_id', models.IntegerField()),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type_created', to='stock.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_type_updated', to='stock.user')),
            ],
            options={
                'db_table': 'product_type',
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('production_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_at', models.DateTimeField()),
                ('status', models.CharField(max_length=60)),
                ('total_milk_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_created', to='stock.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stock_updated', to='stock.user')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.producttype')),
            ],
            options={
                'db_table': 'product_stock',
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('sold', 'Sold'), ('expired', 'Expired'), ('contamination', 'Contamination')], max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('product_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.productstock')),
            ],
            options={
                'db_table': 'product_stock_history',
            },
        ),
    ]
