# Generated by Django 5.1.3 on 2025-05-14 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_user_remove_notification_feed_stock_and_more'),
        ('stock', '0002_alter_stockhistory_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.user'),
        ),
    ]
