# Generated by Django 5.1.3 on 2025-04-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('material_purchase', 'Material Purchase'), ('feed_purchase', 'Feed Purchase'), ('medicine_purchase', 'Medicine Purchase'), ('employee_salary', 'Employee Salary'), ('operational', 'Operational'), ('equipment_purchase', 'Equipment Purchase'), ('marketing', 'Marketing'), ('other', 'Other')], max_length=20),
        ),
    ]
