from .farmers import farmers_bp
from .cows import cows_bp
from .raw_milks import raw_milks_bp
from .supervisors import supervisors_bp
from .admins import admins_bp
from .auth import auth_bp
from .blog import blogs_bp
from .daily_milk_totals import daily_milk_totals_bp
from .topicBlogs import topic_blogs_bp
from .galleries import galleries_bp