name: dairytrack_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^4.2.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.4.0
  file_picker: ^10.1.9
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  google_maps_flutter: ^2.12.2
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.5.0
  mockito: ^5.4.6
  open_file: ^3.2.1
  path_provider: ^2.0.15
  permission_handler: ^11.3.0
  provider: ^6.1.5
  share_plus: ^11.0.0
  shared_preferences: ^2.0.15
  timezone: ^0.10.1
  url_launcher: ^6.3.1
  excel: ^2.1.0
  pdf: ^3.10.4
  printing: ^5.12.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

# Gunakan flutter_icons sebagai key untuk konfigurasi (sesuai dokumentasi)
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo.png"
  min_sdk_android: 21
