# Generated by Django 5.1.3 on 2025-05-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dummy_field',
            field=models.BooleanField(default=False),
        ),
    ]
