# Generated by Django 5.1.3 on 2025-05-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='dummy_field',
        ),
    ]
